// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: unistream.proto
#ifndef GRPC_unistream_2eproto__INCLUDED
#define GRPC_unistream_2eproto__INCLUDED

#include "unistream.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace centrifugal {
namespace centrifugo {
namespace unistream {

class CentrifugoUniStream final {
 public:
  static constexpr char const* service_full_name() {
    return "centrifugal.centrifugo.unistream.CentrifugoUniStream";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::centrifugal::centrifugo::unistream::Push>> Consume(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::centrifugal::centrifugo::unistream::Push>>(ConsumeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::centrifugal::centrifugo::unistream::Push>> AsyncConsume(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::centrifugal::centrifugo::unistream::Push>>(AsyncConsumeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::centrifugal::centrifugo::unistream::Push>> PrepareAsyncConsume(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::centrifugal::centrifugo::unistream::Push>>(PrepareAsyncConsumeRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Consume(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest* request, ::grpc::ClientReadReactor< ::centrifugal::centrifugo::unistream::Push>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::centrifugal::centrifugo::unistream::Push>* ConsumeRaw(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::centrifugal::centrifugo::unistream::Push>* AsyncConsumeRaw(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::centrifugal::centrifugo::unistream::Push>* PrepareAsyncConsumeRaw(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::centrifugal::centrifugo::unistream::Push>> Consume(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::centrifugal::centrifugo::unistream::Push>>(ConsumeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::centrifugal::centrifugo::unistream::Push>> AsyncConsume(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::centrifugal::centrifugo::unistream::Push>>(AsyncConsumeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::centrifugal::centrifugo::unistream::Push>> PrepareAsyncConsume(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::centrifugal::centrifugo::unistream::Push>>(PrepareAsyncConsumeRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Consume(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest* request, ::grpc::ClientReadReactor< ::centrifugal::centrifugo::unistream::Push>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::centrifugal::centrifugo::unistream::Push>* ConsumeRaw(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request) override;
    ::grpc::ClientAsyncReader< ::centrifugal::centrifugo::unistream::Push>* AsyncConsumeRaw(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::centrifugal::centrifugo::unistream::Push>* PrepareAsyncConsumeRaw(::grpc::ClientContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Consume_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Consume(::grpc::ServerContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest* request, ::grpc::ServerWriter< ::centrifugal::centrifugo::unistream::Push>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_Consume : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Consume() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Consume() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consume(::grpc::ServerContext* /*context*/, const ::centrifugal::centrifugo::unistream::ConnectRequest* /*request*/, ::grpc::ServerWriter< ::centrifugal::centrifugo::unistream::Push>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConsume(::grpc::ServerContext* context, ::centrifugal::centrifugo::unistream::ConnectRequest* request, ::grpc::ServerAsyncWriter< ::centrifugal::centrifugo::unistream::Push>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Consume<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Consume : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Consume() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::centrifugal::centrifugo::unistream::ConnectRequest, ::centrifugal::centrifugo::unistream::Push>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::centrifugal::centrifugo::unistream::ConnectRequest* request) { return this->Consume(context, request); }));
    }
    ~WithCallbackMethod_Consume() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consume(::grpc::ServerContext* /*context*/, const ::centrifugal::centrifugo::unistream::ConnectRequest* /*request*/, ::grpc::ServerWriter< ::centrifugal::centrifugo::unistream::Push>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::centrifugal::centrifugo::unistream::Push>* Consume(
      ::grpc::CallbackServerContext* /*context*/, const ::centrifugal::centrifugo::unistream::ConnectRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Consume<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Consume : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Consume() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Consume() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consume(::grpc::ServerContext* /*context*/, const ::centrifugal::centrifugo::unistream::ConnectRequest* /*request*/, ::grpc::ServerWriter< ::centrifugal::centrifugo::unistream::Push>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Consume : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Consume() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Consume() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consume(::grpc::ServerContext* /*context*/, const ::centrifugal::centrifugo::unistream::ConnectRequest* /*request*/, ::grpc::ServerWriter< ::centrifugal::centrifugo::unistream::Push>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConsume(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Consume : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Consume() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->Consume(context, request); }));
    }
    ~WithRawCallbackMethod_Consume() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consume(::grpc::ServerContext* /*context*/, const ::centrifugal::centrifugo::unistream::ConnectRequest* /*request*/, ::grpc::ServerWriter< ::centrifugal::centrifugo::unistream::Push>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* Consume(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Consume : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_Consume() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::centrifugal::centrifugo::unistream::ConnectRequest, ::centrifugal::centrifugo::unistream::Push>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::centrifugal::centrifugo::unistream::ConnectRequest, ::centrifugal::centrifugo::unistream::Push>* streamer) {
                       return this->StreamedConsume(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_Consume() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Consume(::grpc::ServerContext* /*context*/, const ::centrifugal::centrifugo::unistream::ConnectRequest* /*request*/, ::grpc::ServerWriter< ::centrifugal::centrifugo::unistream::Push>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedConsume(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::centrifugal::centrifugo::unistream::ConnectRequest,::centrifugal::centrifugo::unistream::Push>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Consume<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_Consume<Service > StreamedService;
};

}  // namespace unistream
}  // namespace centrifugo
}  // namespace centrifugal


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_unistream_2eproto__INCLUDED
